# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker




    pool:
      vmImage: ubuntu-latest
- task: CmdLine@2
  inputs:
    script: |
      az login
      az group create --name myResourceGroup --location Eastasia
      az acr create --resource-group myResourceGroup --name myacrrepo31 --sku Standard --location Eastasia

    
        
        
