# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script:
    echo Hello, world!
    echo stared by user $(NAME)
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Bash@3
  displayName: VMCreate
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      az login --tenant 30b9e62d-f376-4116-9d17-bc4a7bb87915
      az account show --output yaml
      az group create --name ajithrg --location eastasia
      az network vnet create -g ajithrg -n ajithvnet --address-prefix 10.0.0.0/16 \
                --subnet-name ajithsubnet --subnet-prefix 10.0.0.0/24
      az network nsg create -g ajithrg -n ajithnsg
      az network nic create -g ajithrg --vnet-name ajithvnet --subnet ajithsubnet -n ajithnic
      az network nic ip-config create -g ajithrg -n binduipConfig --nic-name ajithnic --make-primary
      az vm create -n ajithmaster -g ajithrg --image UbuntuLTS --public-ip-sku Standard --custom-data jenkins.txt --authentication-type password --admin-username azureuser --admin-password Ajith@123456789
      az vm open-port --port 8080 --resource-group ajithrg --name ajithmaster
