# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script:
    echo Hello, world!
    echo stared by user $(NAME)
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Bash@3
  displayName: VMCreate
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      az login 
      az group create --name SResourceGroup --location eastasia
      az acr create --resource-group SResourceGroup --name sacrrepo --sku Standard --location eastasia
      az aks create --resource-group SResourceGroup --name SAKSCluster --node-count 2 --enable-addons monitoring --generate-ssh-keys
      az aks show --name SAKSCluster --resource-group SResourceGroup
       az aks get-credentials --resource-group SResourceGroup --name SAKSCluster --overwrite-existing
