apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: ajjuacrrepo.azurecr.io/nginx-app
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-app
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: nginx-app
